// Get all Users
GET http://localhost:3000/users


###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "mussab@a.com",
    "name": "Mussab",
    "password": "123"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ammar@a.com",
    "password": "123"
}

###

PUT http://localhost:3000/users/connect
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIxODg5NTYzLCJleHAiOjE2MjE4OTMxNjN9.WHCvLglgPx4pfl42XjQjAXd9cC2uGZGj4DJUyacmLZU

{
    "connectId" : "60ac11f8f3a76824c8fb9823"
}



/// =========== POSTS =============

###

// Create Post
POST http://localhost:3000/posts/make
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIxOTg3NTYzLCJleHAiOjE2MjE5OTExNjN9.wDzjEV4rqpgZarj2tx8ykPNwmZ4XPdYAIqR86QCafMc

{
    "content": "ammar's post # 34"
}

###

// Get all Posts
GET http://localhost:3000/post/getUserPosts
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIxOTgzOTM2LCJleHAiOjE2MjE5ODc1MzZ9.avT5cIiIU4i6o-YvYor2fswA1GOQfe4rLR_H6Ad0Zuo

###

GET http://localhost:3000/post/getConPosts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIxOTgzOTM2LCJleHAiOjE2MjE5ODc1MzZ9.avT5cIiIU4i6o-YvYor2fswA1GOQfe4rLR_H6Ad0Zuo

###

PUT http://localhost:3000/post/likePost
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11c3NhYkBhLmNvbSIsInVzZXJJZCI6IjYwYWMxMWY4ZjNhNzY4MjRjOGZiOTgyMyIsImlhdCI6MTYyMTg4OTY4NywiZXhwIjoxNjIxODkzMjg3fQ.E2o5I8O094A3Ys_jBpFJ7p4jPFU4I_uvRT47BjHiTrY
Content-Type: application/json

{
    "postId" : "60ac122bf3a76824c8fb9825"
}

###
PUT http://localhost:3000/users/addBio
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11c3NhYkBhLmNvbSIsInVzZXJJZCI6IjYwYWMxMWY4ZjNhNzY4MjRjOGZiOTgyMyIsImlhdCI6MTYyMTk4MTc1NywiZXhwIjoxNjIxOTg1MzU3fQ.WBnAGaNDzAyXpr91ngk11VENO-yWwCItucPt0y7PY2U
Content-Type: application/json

{
    "bio" : "Im Mussab"
}

###
GET http://localhost:3000/users/getUser
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11c3NhYkBhLmNvbSIsInVzZXJJZCI6IjYwYWMxMWY4ZjNhNzY4MjRjOGZiOTgyMyIsImlhdCI6MTYyMTk4MTc1NywiZXhwIjoxNjIxOTg1MzU3fQ.WBnAGaNDzAyXpr91ngk11VENO-yWwCItucPt0y7PY2U





