// Get all Users
GET http://localhost:3000/users


###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "mussab@a.com",
    "name": "Mussab",
    "password": "123"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ammar@a.com",
    "password": "123"
}

###

PUT http://localhost:3000/users/connect
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIxODg5NTYzLCJleHAiOjE2MjE4OTMxNjN9.WHCvLglgPx4pfl42XjQjAXd9cC2uGZGj4DJUyacmLZU

{
    "connectId" : "60ac11f8f3a76824c8fb9823"
}



/// =========== POSTS =============

###

// Create Post
POST http://localhost:3000/posts/make
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIyMDI4MDgzLCJleHAiOjE2MjIwMzE2ODN9.kXl16WBc5frMCo1cZNWHwT5UfW6vAUv3n6WzlfjdGi0

{
    "content": "So I was there with my bruddah in the jam"
}

###

// Get all Posts
GET http://localhost:3000/posts/getUserPosts
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIyMDI5NzY4LCJleHAiOjE2MjIwMzMzNjh9.T3xhe9aTyYs_-WlZPyYNnOu0G2WvC3o1iyAG_3dR7wY

###

GET http://localhost:3000/posts/getConPosts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIyMDMxNjU1LCJleHAiOjE2MjIwMzUyNTV9.TxjhPNwJOIgRdH5gNa7QvjQWTY_vmjPlnck5Kd4GH_s

###

PUT http://localhost:3000/posts/likePost
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIyMDMxNjU1LCJleHAiOjE2MjIwMzUyNTV9.TxjhPNwJOIgRdH5gNa7QvjQWTY_vmjPlnck5Kd4GH_s
Content-Type: application/json

{
    "postId" : "60ae404a3ba272215c841d7f"
}

###
PUT http://localhost:3000/users/addBio
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIyMDM0NzgwLCJleHAiOjE2MjIwMzgzODB9.qOUVVOiXOdBwoOFFqeBvVLvW9nF5J2zOZ5nBJhS-nPY
Content-Type: application/json

{
    "bio" : "Im Mussab"
}

###
GET http://localhost:3000/users/getUser
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIyMDM0NzgwLCJleHAiOjE2MjIwMzgzODB9.qOUVVOiXOdBwoOFFqeBvVLvW9nF5J2zOZ5nBJhS-nPY

###

GET http://localhost:3000/posts/getPostById/60ae404a3ba272215c841d7f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtbWFyQGEuY29tIiwidXNlcklkIjoiNjBhYzEyMGVmM2E3NjgyNGM4ZmI5ODI0IiwiaWF0IjoxNjIyMDM0NzgwLCJleHAiOjE2MjIwMzgzODB9.qOUVVOiXOdBwoOFFqeBvVLvW9nF5J2zOZ5nBJhS-nPY
Content-Type: application/json




